version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "mysql://dev:dev@database:3306/itransition?serverVersion=mariadb-8.0.32&charset=utf8mb4"
    depends_on:
      - database
    networks:
      - itransition-network

  database:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: itransition
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - itransition-network

networks:
  itransition-network:
    driver: bridge
